version: '3.8'

services:
  flask:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    depends_on:
      - redis
      
  celery_worker:
    build: .
    command: celery -A celery_config.celery_app worker --loglevel=INFO- -pidfile=''
    depends_on:
      - redis
    env_file:
      - .env
